spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_manager?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234567
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
